{% set name = "partial-json-parser" %}
{% set version = "0.2.1.1.post7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/partial_json_parser-{{ version }}.tar.gz
  sha256: 86590e1ba6bcb6739a2dfc17d2323f028cb5884f4c6ce23db376999132c9a922

build:
  entry_points:
    - json-playground = partial_json_parser.playground:main
  skip: true # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pdm-backend
    - pip
  run:
    - python

test:
  imports:
    - partial_json_parser
  commands:
    - pip check
  requires:
    - pip

about:
  # https://promplate.dev/partial-json-parser does not seem to have anything other
  # than an animated example of the package working, without any further information. Github
  # seems like a more fitting homepage, but this is the homepage listed in the pyproject.toml.
  home: https://promplate.dev/partial-json-parser
  summary: Parse partial JSON generated by LLM
  description: Parse partial JSON generated by LLM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://github.com/promplate/partial-json-parser
  dev_url: https://github.com/promplate/partial-json-parser

extra:
  recipe-maintainers:
    - maresb
